# 10 is Frankfurt
region: 10 
app_host: 138.59.61.4
tag: project_foo
provider: linode
root_pass: <PASS> 
hosts:
# data servers
# rs0  
  - name: rs0-data1-mongodb
    #Linode 12288: 192GB Storage, 6 CPU Cores, 8TB XFER, $80/mo or (.12/hr)
    size: 5 
    
  - name: rs0-data2-mongodb
    size: 5
    
  - name: rs0-arb-mongodb
    # Linode 1024
    size: 1 
#rs1
  - name: rs1-data1-mongodb
    size: 5
    
  - name: rs1-data2-mongodb
    size: 5
    
  - name: rs1-arb-mongodb
    size: 1
    

# config + arbiters    
  - name: config1-mongodb
    size: 1
  - name: config2-mongodb
    size: 1
  - name: config3-mongodb
    size: 1
# routers  
  - name: router1-mongodb
    size: 1
    tag: Fooo
  - name: router2-mongodb
    size: 1
    tag: Bar
  
replicas:
  - name: routers
    type: router
    members:
      - host: router1-mongodb
      - host: router2-mongodb
  - name: mongoc
    type: config
    members:
      - host: config1-mongodb
        type: config
        primary: 1
      - host: config2-mongodb
        type: config
      - host: config3-mongodb
        type: config    
  - name: rs0
    type: shard
    members:
      - host: rs0-data1-mongodb
        port: 27030      
        primary: 1
      - host: rs0-data2-mongodb
        port: 27031      
      - host: rs0-arb-mongodb
        arbiter: 1
        port: 27032      
  - name: rs1
    type: shard    
    members:
      - host: rs1-data1-mongodb
        port: 27030      
        primary: 1
      - host: rs1-data2-mongodb
        port: 27031      
      - host: rs1-arb-mongodb
        arbiter: 1          
        port: 27032      
